<a href="https://colab.research.google.com/github/ronakbihani123/NLP/blob/main/bow_%2C_tfidf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. bag of words
# we use countvectorization

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({"text":['people watch cricket' , 'player was player',
                            'people write comment' , 'cricket play comment'] , 'output': [1,1,0,0]})

In [ ]:
df

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [ ]:
# # people watch cricket player was write comment platform
# [111000000]
# [00021000]
# [10000110]
# [00100011]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]

In [ ]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [ ]:
# 2. N-grams

In [ ]:
# cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
v = CountVectorizer(ngram_range=(1,2))
# v = CountVectorizer(ngram_range=(2,2))
#

In [ ]:
bow = v.fit_transform(df["text"])

In [ ]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [ ]:
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}

In [ ]:
# TF(term frequency)
# 2. IDF(Inverse Document Frequency)

In [ ]:
# TF(t,d) = (Number of occurences of term t in document d)/
# (total number of terms in the document d)
# example --->
# d1 =people watch cricket

# tf(people , d1) = 1/3

# d2 = match was match
# df(match , d2) = 2/3

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']