<a href="https://colab.research.google.com/github/ronakbihani123/NLP/blob/main/POS_tagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# POS Tagging in NLP

# POS tagging means part of speech tagging
# it is an NLP technique where each word in a sentence is assigned its
# grammatical role such as :
# NOUN
# verb
# adjective
# adverb
# pronoun
# preposition
# conjunction
# interjection

In [ ]:
# # why pos tagging is important ?

# # pos tagging is used in :
# # text classiffication
# # chatbots
# # machine translation
# # speech recognition
# # namer entity recognition
# # sentiment analysis
# grammar checking

In [ ]:
# from typing import NoReturn
# common pos tags

# POS Tag      |      Meaning

# NN         |      Noun
# NNS         |     plural noun
# NNP        |     proper noun
# VB          |  verb
# VBD        |  verb past tense
# VBG           | verb gerund
# jj          |  adjective
# rb           | adverb
# PRP          | Pronoun
# IN             | preposition

In [ ]:
# from IPython.core.inputtransformer2 import TokenTransformBase
# working process of pos tagging :::::::
# 1. sentence is divided into Token
# 2 . NLP model checks grammar / context
# 3. appropriate POs tag is assigned to each word

In [ ]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.4.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 60.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import spacy

# Load english model
nlp = spacy.load("en_core_web_sm")

# input text
doc = nlp("Sourabh is learning NLP")

# POS tagging
for token in doc:
  print(token.text, "-->", token.pos_)

Sourabh --> PROPN
is --> AUX
learning --> VERB
NLP --> PROPN

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp("Ronak plays cricket")

for token in doc:
  print(token.text, "-->", token.pos_)

Ronak --> PROPN
plays --> VERB
cricket --> NOUN

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp("Sourabh is learning NLP")

for token in doc:
  print("word:" , token.text,
        "| POS:" , token.pos_,
        "|TAG:" , token.tag_)

word: Sourabh | POS: PROPN |TAG: NNP
word: is | POS: AUX |TAG: VBZ
word: learning | POS: VERB |TAG: VBG
word: NLP | POS: PROPN |TAG: NNP

In [ ]:
# visualizing POS tagging

In [ ]:
import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("Sourabh is learning NLP")

displacy.serve(doc, style="dep")

/usr/local/lib/python3.12/dist-packages/spacy/displacy/__init__.py:107: UserWarning: [W011] It looks like you're calling displacy.serve from within a Jupyter notebook or a similar environment. This likely means you're already running a local web server, so there's no need to make displaCy start another one. Instead, you should be able to replace displacy.serve with displacy.render to show the visualization.
  warnings.warn(Warnings.W011)

Using the 'dep' visualizer
Serving on http://0.0.0.0:5000 ...

Shutting down server on port 5000.

In [ ]:
# IMDB Dataset ---- clean ----- 1 row -paragraph ----Pos tag , NER extract

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df["review"] = df["review"].str.lower()

In [ ]:
import re
def remove_html_tags(text):
  pattern = re.compile("<.*?>")
  return pattern.sub(r"", text)

In [ ]:
df["review"] = df["review"].apply(remove_html_tags)

In [ ]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
def remove_urls(text):
  pattern  = re.compile(r"https://\S+|www\. \S+")
  return pattern.sub(r"", text)

In [ ]:
text = "For notebook click https://www.deture.com/delta/note1234acc"
remove_urls(text)

'For notebook click '

In [ ]:
df["review"] = df["review"].apply(remove_urls)

In [ ]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude= string.punctuation

In [ ]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char , "")
  return text

In [ ]:
text = 'string. with. Punctuation?'

In [ ]:
remove_punc(text)

'string with Punctuation'

In [ ]:
df["review"] = df["review"].apply(remove_punc)

In [ ]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
paragraph = df["review"][3]

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp(paragraph)

for token in doc:
  print(token.text , "----->" , token.pos_)

basically -----> ADV
there -----> PRON
s -----> VERB
a -----> DET
family -----> NOUN
where -----> SCONJ
a -----> DET
little -----> ADJ
boy -----> NOUN
jake -----> PROPN
thinks -----> VERB
there -----> PRON
s -----> VERB
a -----> DET
zombie -----> NOUN
in -----> ADP
his -----> PRON
closet -----> NOUN
  -----> SPACE
his -----> PRON
parents -----> NOUN
are -----> AUX
fighting -----> VERB
all -----> DET
the -----> DET
timethis -----> DET
movie -----> NOUN
is -----> AUX
slower -----> ADJ
than -----> ADP
a -----> DET
soap -----> NOUN
opera -----> NOUN
and -----> CCONJ
suddenly -----> ADV
jake -----> PROPN
decides -----> VERB
to -----> PART
become -----> VERB
rambo -----> ADJ
and -----> CCONJ
kill -----> VERB
the -----> DET
zombieok -----> NOUN
first -----> ADV
of -----> ADP
all -----> PRON
when -----> SCONJ
you -----> PRON
re -----> AUX
going -----> VERB
to -----> PART
make -----> VERB
a -----> DET
film -----> NOUN
you -----> PRON
must -----> AUX
decide -----> VERB
if -----> SCONJ
its -----> PRON
a -----> DET
thriller -----> NOUN
or -----> CCONJ
a -----> DET
drama -----> NOUN
as -----> ADP
a -----> DET
drama -----> NOUN
the -----> DET
movie -----> NOUN
is -----> AUX
watchable -----> ADJ
parents -----> NOUN
are -----> AUX
divorcing -----> VERB
  -----> SPACE
arguing -----> VERB
like -----> INTJ
in -----> ADP
real -----> ADJ
life -----> NOUN
and -----> CCONJ
then -----> ADV
we -----> PRON
have -----> VERB
jake -----> PROPN
with -----> ADP
his -----> PRON
closet -----> NOUN
which -----> PRON
totally -----> ADV
ruins -----> VERB
all -----> DET
the -----> DET
film -----> NOUN
i -----> PRON
expected -----> VERB
to -----> PART
see -----> VERB
a -----> DET
boogeyman -----> NOUN
similar -----> ADJ
movie -----> NOUN
and -----> CCONJ
instead -----> ADV
i -----> PRON
watched -----> VERB
a -----> DET
drama -----> NOUN
with -----> ADP
some -----> DET
meaningless -----> ADJ
thriller -----> NOUN
spots3 -----> NOUN
out -----> ADP
of -----> ADP
10 -----> NUM
just -----> ADV
for -----> ADP
the -----> DET
well -----> ADV
playing -----> VERB
parents -----> NOUN
  -----> SPACE
descent -----> NOUN
dialogs -----> NOUN
as -----> ADP
for -----> ADP
the -----> DET
shots -----> NOUN
with -----> ADP
jake -----> PROPN
just -----> ADV
ignore -----> VERB
them -----> PRON

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(paragraph)
for ent in doc.ents:
  print(ent.text , "------>" , ent.label_)

first ------> ORDINAL
10 ------> CARDINAL